### ISSUE TITLE
require('X') broken after 1.0.0

### ISSUE THREAD

**Issue by mim-Armand** [electron-userland/electron-prebuilt#134]
Requiring method seems to be broken from 1.0.0.
Works on 0.37.8 but stops working on later releases (tested on 1.0.0 and 1.1.0)

`Uncaught Error: Cannot find module 'remote'`

,m

**Comment by szwacz** [comment]
Please read release notice: https://github.com/electron/electron/releases/tag/v1.0.0
Method of requireing those APIs have changed.

**Comment by mim-Armand** [comment]
Thanks @szwacz, so for future reference here is the change:

For instance, Instead of requiring remote, require remote method from electron (methods have no exposure any more):
``` javascript
const remote = require('electron').remote;
```

,m
