### ISSUE TITLE
error at prebuilt 1.20, but run on 0.35

### ISSUE THREAD

**Issue by fthamura** [electron-userland/electron-prebuilt#140]
I have a small code, that run well in prebuilt 0.35, but when I upgrade to 1.2.0, get error.

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/home/mervo/electron/electron-guide/0-helloworld/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mervo/electron/electron-guide/0-helloworld/main.js:3:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12

is there a bugs in 1.2.0?

**Comment by TimNZ** [comment]
All the helper injected require modules were removed in 1.0, you'll have to do "const {app} = require('electron')", along with browser-window etc

**Comment by kevinsawicki** [comment]
You will need to update your Electron API calls for the 1.0 API as @TimNZ mentioned.

See http://electron.atom.io/blog/2015/11/17/electron-api-changes for more details, closing this out.
